### PR TITLE
Uncertainty merge

### PR DESCRIPTION
**Pull request by jasonjewik**
Merged climate_uncertainty repo which had CRPS, MC dropout, and parametric prediction implementations. Requires download of constants. For example,
```
download(root = "/content/drive/MyDrive/Climate/.climate_tutorial", source = "weatherbench", variable = "constants", dataset = "era5", resolution = "5.625")
```
Colab proof that this branch works: https://colab.research.google.com/drive/1Eb0pnpyhMxmNmtf7p_eXyG5Fl37wmtvU?usp=sharing.

Also, the call to `visualize` in the last code cell failed, but I suspect that it would have also failed in the original notebook since it is neither imported from the package nor defined in the notebook.

### CODE REVIEW

**Review by Hritikbansal — COMMENTED** [review]
Do we really need mcdropout as an argument to the forward function? If not, then can we make it a member of the class instead?
Something like self.mcdropout

**Review by Hritikbansal — COMMENTED** [review]
In resnet.py, do we need the commented part at the end of the script?

**Review by jasonjewik — COMMENTED** [review]
Just realized that I pushed the `.ipynb_checkpoints` and the `.ckpt` files. Should those be deleted?

**Comment by jasonjewik** [comment]
> Do we really need mcdropout as an argument to the forward function? If not, then can we make it a member of the class instead? Something like self.mcdropout
OK. That sounds good to me. I'll make that change.

> In resnet.py, do we need the commented part at the end of the script?
No, I can delete this.

**Pull request closed without merging**
